name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}

jobs:
  metrics-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jorgepiloto
          template: classic
          filename: img/metrics-stats.svg
          base: header, activity, community, repositories
          config_timezone: Europe/Paris

  metrics-achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jorgepiloto
          template: classic
          base: ""
          filename: img/metrics-achievements.svg
          config_timezone: Europe/Paris
          plugin_achievements: yes
          plugin_achievements_limit: 6
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          repositories: 200
