name: Updater
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  metrics-stats:
    name: Metrics stats
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jorgepiloto
          template: classic
          filename: metrics-stats.svg
          base: header, activity, community, repositories
          config_timezone: Europe/Madrid

  metrics-achievements:
    runs-on: ubuntu-latest
    name: Metrics achievements
    needs: [metrics-stats]
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jorgepiloto
          template: classic
          base: ""
          filename: metrics-achievements.svg
          config_timezone: Europe/Madrid
          plugin_achievements: yes
          plugin_achievements_limit: 6
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          repositories: 200

  update-readme-with-blog:
    name: Latest posts
    runs-on: ubuntu-latest
    needs: [metrics-stats, metrics-achievements]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Collect latest posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://jorgemartinez.space/index.xml"
